baseURL = 'https://comocamp.org/'
languageCode = 'en-us'
title = 'ComoCamp 2026'

enableInlineShortcodes = true
enableRobotsTXT = true

extensions = [
  "hardLineBreak", # newlines result in line breaks
]

[menu]
[[menu.main]]
  name = 'What is Collaborative Modeling?'
  pageRef = 'como'
  weight = 1
[[menu.main]]
  name = 'ComoCamp'
  pageRef = 'camp'
  weight = 2
[[menu.main]]
  name = 'Community'
  pageRef = 'community'
  weight = 3
[[menu.main]]
  name = 'Location'
  pageRef = 'location'
  weight = 4
# [[menu.main]]
#   name = 'Program'
#   pageRef = 'program'
#   weight = 5
[[menu.main]]
  name = 'Sponsors'
  pageRef = 'supporters'
  weight = 6
[[menu.main]]
  name = 'Team'
  pageRef = 'team'
  weight = 7
[[menu.main]]
  name = 'How to participate'
  pageRef = 'participation'
  weight = 8

[Params]
	DateForm = "2006-01-02"
  SaveTheDate = true
  Sections = ["hero", "como", "camp", "community", "bring-your-topics", "location", "program", "participation", "faqs", "supporters", "supporters-2", "media-partners", "team", "we-are-looking-forward"]
